### PR TITLE
Modify pdb_rslice.py to NOT print PDB headers

### PR DESCRIPTION
**Pull request by CunliangGeng**

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
@CunliangGeng I like consistency. I'm OK with this change, provided **all** scripts behave the same. So, if you want to go ahead and change this for everyone, I'll gladly accept!

**Comment by amjjbonvin** [comment]
But sometimes you might want to keep the header... may-be a flag for this option then? 

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Comment by JoaoRodrigues** [comment]
@amjjbonvin Would a strip_header tool be more helpful? One more tool, but easier to write than flags everywhere.

**Comment by amjjbonvin** [comment]
Good idea!

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Comment by JoaoRodrigues** [comment]
Commit 66242cd solves this.

**Pull request closed without merging**
