### PR TITLE
pdb_delatom.py v0.1

### PR DESCRIPTION
**Pull request by joaomcteixeira**
- Deletes given atom type from PDB file.
- Atom names input is case sensitive
- Scans ATOM and HETATM lines
- accepts and output to pipe

### CODE REVIEW

**Comment by amjjbonvin** [comment]
How should we go about making this version of pdb-tools and the haddocking one consistent? Do we want that? The one in SBGrid comes from haddocking.

**Comment by joaomcteixeira** [comment]
Such answer lies a bit outside my knowledge, but, what I can address is that we have kept all pdb-tools scripts within the same structure:

`pdb_SCRIPT.py -OPTIONS INPUT.pdb`

In this way they can be executed within the same API structure, if that's the case of HADDOCK.

On this regard, there's an issue on the unification of the pdb-tools API: #19 

Would there be a problem if in this repository there are scripts that are not used for haddocking if those follow the same API of the original repository?

**Comment by JoaoRodrigues** [comment]
We should find a way of keeping both repositories in sync, automatically.
Usually I do it - when I push to one I push to both. I could also just move
this to haddocking and delete the other repo. I'll handle all these changes
this week and sync them.

A terça, 16/10/2018, 04:50, João M.C. Teixeira <notifications@github.com>
escreveu:

**Comment by JoaoRodrigues** [comment]
Added in version 2 as `pdb_delatom.py`. Deletes based on element of the column. Plays well with `pdb_element` which attributes elements based on atom names.

@amjjbonvin After I fix all these issues, etc, I will merge all changes with the haddocking branch and transfer the 'upstream' status to that branch.

**Pull request closed without merging**
